//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group43.WordCountSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordCountSvc.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWordCount", ReplyAction="http://tempuri.org/IService1/GetWordCountResponse")]
        string GetWordCount(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWordCount", ReplyAction="http://tempuri.org/IService1/GetWordCountResponse")]
        System.Threading.Tasks.Task<string> GetWordCountAsync(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FilterContent", ReplyAction="http://tempuri.org/IService1/FilterContentResponse")]
        string FilterContent(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FilterContent", ReplyAction="http://tempuri.org/IService1/FilterContentResponse")]
        System.Threading.Tasks.Task<string> FilterContentAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Group43.WordCountSvc.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Group43.WordCountSvc.IService1>, Group43.WordCountSvc.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWordCount(string content) {
            return base.Channel.GetWordCount(content);
        }
        
        public System.Threading.Tasks.Task<string> GetWordCountAsync(string content) {
            return base.Channel.GetWordCountAsync(content);
        }
        
        public string FilterContent(string input) {
            return base.Channel.FilterContent(input);
        }
        
        public System.Threading.Tasks.Task<string> FilterContentAsync(string input) {
            return base.Channel.FilterContentAsync(input);
        }
    }
}
