//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group43.MyEbayServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyEbayServiceReference.IMyEbayService1")]
    public interface IMyEbayService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEbayService1/SearchItem", ReplyAction="http://tempuri.org/IMyEbayService1/SearchItemResponse")]
        string SearchItem(string queryItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEbayService1/SearchItem", ReplyAction="http://tempuri.org/IMyEbayService1/SearchItemResponse")]
        System.Threading.Tasks.Task<string> SearchItemAsync(string queryItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEbayService1/GetItem", ReplyAction="http://tempuri.org/IMyEbayService1/GetItemResponse")]
        string GetItem(string listingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEbayService1/GetItem", ReplyAction="http://tempuri.org/IMyEbayService1/GetItemResponse")]
        System.Threading.Tasks.Task<string> GetItemAsync(string listingId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyEbayService1Channel : Group43.MyEbayServiceReference.IMyEbayService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyEbayService1Client : System.ServiceModel.ClientBase<Group43.MyEbayServiceReference.IMyEbayService1>, Group43.MyEbayServiceReference.IMyEbayService1 {
        
        public MyEbayService1Client() {
        }
        
        public MyEbayService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyEbayService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyEbayService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyEbayService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SearchItem(string queryItem) {
            return base.Channel.SearchItem(queryItem);
        }
        
        public System.Threading.Tasks.Task<string> SearchItemAsync(string queryItem) {
            return base.Channel.SearchItemAsync(queryItem);
        }
        
        public string GetItem(string listingId) {
            return base.Channel.GetItem(listingId);
        }
        
        public System.Threading.Tasks.Task<string> GetItemAsync(string listingId) {
            return base.Channel.GetItemAsync(listingId);
        }
    }
}
